highlighter: rouge
url: http://www.bephpug.de
name: Berlin PHP Usergroup
timezone: Europe/Berlin
markdown: kramdown
future: true
meetupbutton: 3764k5il39e0tsdvm7l04gomc # live
#meetupbutton: ukhtv4jccfm8lo5rguqrgp78qo # local

exclude:
  - .editorconfig
